# Generated by Django 5.0.1 on 2026-05-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_listing', 'New Listing'), ('new_comment', 'New Comment'), ('reply', 'Reply to Comment'), ('rating', 'New Rating'), ('booking', 'Booking Update'), ('ticket', 'Ticket Update'), ('event', 'Event Update'), ('system', 'System Notification')], max_length=20),
        ),
    ]
