# Generated by Django 5.0.1 on 2026-01-08 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingimage_image_url_alter_listingimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vibing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vibes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', 'is_vibing'], name='vibes_listing_72839f_idx')],
                'unique_together': {('listing', 'user')},
            },
        ),
    ]
