# Generated by Django 5.0.1 on 2026-01-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_vibe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_range',
            field=models.CharField(choices=[('$', '$ - Budget Friendly'), ('$$', '$$ - Moderate'), ('$$$', '$$$ - Premium'), ('$$$$', '$$$$ - Luxury')], default='$$', max_length=10),
        ),
    ]
