# Generated by Django 5.0.1 on 2026-01-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_phone_alter_listing_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified listings show a verified badge'),
        ),
    ]
