# Generated by Django 5.0.1 on 2026-05-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='app_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='listing',
            name='display_price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_kind',
            field=models.CharField(choices=[('listing', 'Listing'), ('event', 'Event')], default='listing', max_length=20),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_type',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('hero', 'Hero'), ('ticket', 'Ticket')], default='gallery', max_length=20),
        ),
    ]
