# Generated by Django 5.0.1 on 2026-05-18 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_category_icon_listing_app_data_listing_display_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_listings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='saved_listi_user_id_c537b1_idx'), models.Index(fields=['listing', 'created_at'], name='saved_listi_listing_bb8c74_idx')],
                'unique_together': {('listing', 'user')},
            },
        ),
    ]
