# Generated by Django 5.0.1 on 2026-05-18 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_savedlisting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_histories', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_view_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listing_view_history',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', 'viewed_at'], name='listing_vie_user_id_9a97f4_idx'), models.Index(fields=['listing', 'viewed_at'], name='listing_vie_listing_3cba30_idx')],
                'unique_together': {('listing', 'user')},
            },
        ),
    ]
