# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listingviewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='media_kind',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=12),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='listings/videos/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video URL', null=True),
        ),
    ]
