# Generated by Codex on 2026-05-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listingimage_media_kind_listingimage_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingimage',
            options={
                'db_table': 'listing_images',
                'ordering': ['order', '-is_primary', 'created_at'],
            },
        ),
    ]
