# Generated by Django 5.0.1 on 2026-05-20 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_listingimage_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('qr_payload', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('used', 'Used'), ('cancelled', 'Cancelled')], default='confirmed', max_length=16)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-booked_at'],
                'indexes': [models.Index(fields=['user', 'status', 'booked_at'], name='tickets_user_id_231696_idx'), models.Index(fields=['listing', 'status'], name='tickets_listing_7b5ddd_idx')],
                'unique_together': {('listing', 'user')},
            },
        ),
    ]
