# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingMediaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_guard', models.BooleanField(default=True, editable=False, unique=True)),
                ('name', models.CharField(default='Global media policy', max_length=80)),
                (
                    'video_retention_days',
                    models.PositiveIntegerField(
                        default=30,
                        help_text='Videos older than this many days are removed automatically. Use 0 to keep them indefinitely.',
                    ),
                ),
                (
                    'cleanup_interval_hours',
                    models.PositiveSmallIntegerField(
                        default=12,
                        help_text='How often automatic cleanup is allowed to run when the app or API is active.',
                    ),
                ),
                ('last_video_cleanup_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'listing_media_policy',
                'verbose_name_plural': 'Listing media policies',
            },
        ),
    ]
