# Generated by Django 5.0.1 on 2026-05-21 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_listingmediapolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingFeedImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(blank=True, max_length=180)),
                ('source', models.CharField(default='app_feed', max_length=40)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_impressions', to='listings.category')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_impressions', to='listings.listing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listing_feed_impressions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='listing_fee_user_id_dc7d8e_idx'), models.Index(fields=['listing', 'created_at'], name='listing_fee_listing_c16e5d_idx'), models.Index(fields=['category', 'created_at'], name='listing_fee_categor_a3ce90_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=180)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_query_logs', to='listings.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_query_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_query_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='search_quer_user_id_df3c21_idx'), models.Index(fields=['query', 'created_at'], name='search_quer_query_45a844_idx'), models.Index(fields=['category', 'created_at'], name='search_quer_categor_ae5427_idx')],
            },
        ),
    ]
