# Generated by Django 5.0.1 on 2026-05-21 10:29

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_listingfeedimpression_searchquerylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ticket',
            name='action_type',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('reservation', 'Reservation'), ('booking', 'Booking'), ('order', 'Order'), ('enquiry', 'Enquiry')], default='ticket', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='ticket',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payer_phone',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_last_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ecocash', 'EcoCash'), ('onemoney', 'OneMoney'), ('innbucks', 'InnBucks'), ('omari', 'Omari')], max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='not_required', max_length=16),
        ),
        migrations.AddField(
            model_name='ticket',
            name='paynow_browser_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='ticket',
            name='paynow_poll_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='ticket',
            name='paynow_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('failed', 'Payment Failed'), ('expired', 'Expired')], default='confirmed', max_length=16),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['reference_code'], name='tickets_referen_5167de_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['paynow_reference'], name='tickets_paynow__96933d_idx'),
        ),
    ]
