# Generated by Django 5.0.1 on 2026-05-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_ticket_unique_together_ticket_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='accepts_internal_payments',
            field=models.BooleanField(default=True),
        ),
    ]
