# Generated by Django 5.0.1 on 2026-05-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_listing_accepts_internal_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_guard', models.BooleanField(default=True, editable=False, unique=True)),
                ('name', models.CharField(default='Mobile app update policy', max_length=80)),
                ('latest_version', models.CharField(default='1.1.0', max_length=24)),
                ('min_required_version', models.CharField(default='1.0.0', max_length=24)),
                ('force_update', models.BooleanField(default=False)),
                ('android_update_url', models.URLField(default='https://bitesnvibes.co.zw')),
                ('ios_update_url', models.URLField(default='https://bitesnvibes.co.zw')),
                ('message', models.TextField(default='A newer Bites & Vibes app is available with important fixes and improvements.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'App version policies',
                'db_table': 'app_version_policy',
            },
        ),
    ]
