# Generated by Django 5.0.1 on 2026-01-08 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='root_parent',
            field=models.ForeignKey(blank=True, help_text='The top-level comment this belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_replies', to='comments.comment'),
        ),
    ]
