# Generated by Django 5.0.1 on 2026-01-10 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_message'),
        ('listings', '0005_listing_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pinned comments appear at the top'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['listing', 'is_pinned'], name='comments_listing_920720_idx'),
        ),
    ]
