# Generated by Django 5.0.1 on 2026-01-10 13:24

import comments.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_add_is_pinned_to_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comment_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm']), comments.models.validate_comment_file_size]),
        ),
    ]
