# Generated by Django 5.0.1 on 2026-01-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emaillogintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
