# Generated by Django 5.0.1 on 2026-05-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pushdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdevice',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='last_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='provider',
            field=models.CharField(choices=[('firebase', 'Firebase Cloud Messaging'), ('expo', 'Expo Push Service')], default='firebase', max_length=20),
        ),
        migrations.AlterField(
            model_name='pushdevice',
            name='token',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AddIndex(
            model_name='pushdevice',
            index=models.Index(fields=['provider', 'is_active'], name='push_device_provide_a6715e_idx'),
        ),
    ]
